language: go
go:
 - 1.5.3
 - release
 - tip

script:
 - go test -v -race -parallel 5 -coverprofile=coverage.txt -covermode=atomic ./

before_install:
  - pip install --user codecov
after_success:
  - codecov
